### PR TITLE
Install targets under RUST_TARGET_SYS mismatch (#147)

### PR DESCRIPTION
**Pull request by Dvergatal**
* Fix TARGET_SYS to RUST_TARGET_SYS variable

### CODE REVIEW

**Comment by Dvergatal** [comment]
@microsoft-github-policy-service agree company="Welotec GmbH"

**Comment by ggjjj** [comment]
azp /run

**Comment by ggjjj** [comment]
@Dvergatal  Is it needed with meta-rust layer?

**Comment by jolting** [comment]
@ggjjj this was solved in my PR by using do_install:append, so that cargo_do_install gets invoked. This solves the compatibility issue between oe-rust and meta-rust.

**Comment by ggjjj** [comment]
Closing this PR as the coming PRs will resolve the compatibility issues.

**Pull request closed without merging**
