### PR TITLE
IotEdge 1.0.9 for Zeus

### PR DESCRIPTION
**Pull request by Siddius**
Updated IoTEdge to version 1.0.9 and Yocto Zeus

### CODE REVIEW

**Comment by Siddius** [comment]
@chli done

**Comment by wmmihaa** [comment]
When can we see this PR approved?

**Comment by myagley** [comment]
We created a `zeus` branch and #45 is to support 1.0.9 on this branch.

**Comment by myagley** [comment]
Thanks for this! I cherry picked it and merged it into the `zeus` branch. I'm going to close this PR because I don't think it's needed any longer.

**Pull request closed without merging**
