### PR TITLE
Update to 1.0.10 for Zeus.

### PR DESCRIPTION
**Pull request by Lexmark-chad**
We ran into an issue running 1.0.9.4 that I logged against iotedge here:

https://github.com/Azure/iotedge/issues/3746

sysinfo 0.9.6 had a bug that was fixed in 0.12.0 which was supposed to be the pinned version of sysinfo for iotedge 1.0.10.  Turns out that was not the case in iotedge-cli, so this PR is to a) provide recipes for 1.0.10 for Zeus, and b) provide the patch that pins sysinfo to 0.12.0 in iotedge-cli.

### CODE REVIEW

**Comment by Chad-McQuillen** [comment]
@myagley , any feedback on this PR?

**Comment by dvescovi1** [comment]
I am looking forward to this merge also.

**Comment by tavaneftekhar** [comment]
@Lexmark-chad I'm curious what the overall process is to generate the correct bb files? I'm attempting to manually upgrade to iotedge 1.1.1, but running `cargo bitbake` on the Azure/iotedge source is giving me slightly different results, and there are many Cargo.toml files throughout the source.

**Comment by Lexmark-chad** [comment]
@tavaneftekhar, if you give us a little time we are in the middle of upgrading to Dunfell and iotedge 1.1.1.  With any luck we'll have a PR that we can submit within a few days.

**Comment by darobs** [comment]
Hi @Lexmark-chad, I just merged the 1.1.1 version of this PR, is it OK to close this PR?

**Comment by Lexmark-chad** [comment]
Yes @darobs, this PR can be closed which I will do now.

**Pull request closed without merging**
