### PR TITLE
fix libssl.so: file not recognized

### PR DESCRIPTION
**Pull request by geoffrey-vl**
fixes: https://github.com/Azure/meta-iotedge/issues/34

### CODE REVIEW

**Comment by myagley** [comment]
I'm going to close and reopen the PR to try to get the checkin build to re-run.

**Comment by geoffrey-vl** [comment]
@myagley thanks, it seems the build is simply timing out which is not so strange considering its a Yocto build. Does the build maintain its build cache, or does it rebuild all entirely from scratch every time?

**Comment by myagley** [comment]
We don't have a build cache setup right now. Each build is independent and its building everything again. What's interesting is the other branches don't time out. They are taking ~2.5 hours.

Perhaps we can get the 1.0.9.4 recipe from the `thud` branch ported over to `sumo`?

**Comment by geoffrey-vl** [comment]
You assume that there is something odd with the sumo version of meta-iotedge? Building the image without iotedge recipe with easily confirm that. But maybe it's something with the Sumo branch of Yocto? 

Anyway, I noticed that all PR's are currently timing out, independently of the branch (and YT version). My guess is that there is something up with the AZ pipeline?

**Review by dvescovi1 — COMMENTED** [review]
this fixed my obscure build issue also

**Comment by dvescovi1** [comment]
really would like to see this PR merged into sumo soon

**Comment by dvescovi1** [comment]
4-6 hours is not unusual for a yocto build on an VM spun up from scratch. I would crank up the timeout value of the job as suggested @geoffrey-vl . I would suggest setting 12hr or so to be safe.

**Comment by geoffrey-vl** [comment]
Either that, or throwing more (Azure) computing power at it.

**Comment by micahl** [comment]
@dvescovi1 is this PR something you still want to pursue or should we close it?

**Comment by dvescovi1** [comment]
> @dvescovi1 is this PR something you still want to pursue or should we close it?

I have no issue, I have moved on.
OK to close it.

**Pull request closed without merging**
